sudo: false
cache:
    directories:
        - "~/.platformio"

language: python
python: "3.7"
install:
    - pip install -U platformio==4.2.0
    - platformio update

matrix:
    include:

      - name: "Desktop flight software, common software, and ground software tests"
        addons:
          apt:
            packages:
            - lcov
            - valgrind
            - cppcheck
        install:
            - pip install -U platformio==4.2.0
            - platformio update
            - sudo gem install coveralls-lcov
        script:
            - ./tools/run_common_software_tests.sh
            - ./tools/run_desktop_flight_tests.sh
            - ./tools/run_ground_tests.sh
        after_success:
            - ./tools/generate_coverage.sh
            - coveralls-lcov --repo-token=${COVERALLS_TOKEN} coverage.info

      - name: "Verify Teensy code compiles for flight software, and ADCS software tests"
        install:
            - pip install -U platformio==4.2.0
            - platformio update
        script:
            - ./tools/verify_teensy_builds.sh
            - ./tools/verify_adcs_builds.sh

      #- name: "Run unit tests on Teensy"
        #script:
            #- platformio remote --agent PANTeensyFarm test -e teensy_ci -v
